#!/usr/bin/env python3
"""Local synthetic-data viewer — run and open http://localhost:7860"""

import json, os, random
from http.server import BaseHTTPRequestHandler, HTTPServer
from urllib.parse import urlparse, parse_qs

DATA_DIR = os.path.dirname(os.path.abspath(__file__))

DATASETS = {
    "friend":           ("synthetic_train_friend_1.jsonl",    "Friend mode",          "Warm, peer-level support. The model acts like an emotionally intelligent friend — casual, present, non-clinical."),
    "therapist":        ("synthetic_train_therapist_.jsonl",  "Therapist mode",       "Structured empathic dialogue with reflective listening, emotional validation, and gentle reframing."),
    "transition":       ("synthetic_train_transition.jsonl",  "Casual → emotional",   "Conversations that start light and pivot to real distress — training the model to notice the shift and follow the user there."),
    "grief":            ("synthetic_train.jsonl",             "Grief / loss",         "Emotionally intense dialogues around bereavement, estrangement, and unspoken love. High complexity scenarios."),
    "casual":           ("synthetic_train_casual.jsonl",      "Casual chat",          "Low-stakes everyday conversation — banter, small talk, venting about mundane things. Keeps the model grounded."),
    "targeted_fixes":   ("synthetic_train_targeted_fixes.jsonl", "Targeted fixes (hand-written)", "30–65 hand-crafted seed examples targeting two known failure modes: Help Mode (model must suggest a named coping strategy) and Memory Recall (model must reference a past person/event from the user's profile)."),
    "targeted_fix_gen": ("synthetic_train_targeted_fix.jsonl",   "Targeted fixes (generated)",   "~3k examples generated by the teacher model (Qwen3-30B) from the hand-written seeds above. Same two failure modes, scaled up."),
}

# Load all data once at startup
_cache = {}

def load_dataset(key):
    if key in _cache:
        return _cache[key]
    fname, _, _ = DATASETS[key]
    path = os.path.join(DATA_DIR, fname)
    rows = []
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                line = line.strip()
                if line:
                    try:
                        rows.append(json.loads(line))
                    except Exception:
                        pass
    _cache[key] = rows
    return rows

def build_summary():
    summary = []
    total = 0
    for key, (fname, label, desc) in DATASETS.items():
        rows = load_dataset(key)
        n = len(rows)
        total += n
        summary.append({"key": key, "label": label, "desc": desc, "count": n})
    return summary, total

HTML = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>MindMate Synthetic Data Viewer</title>
<style>
  :root {
    --bg: #0f0f13;
    --surface: #1a1a22;
    --border: #2e2e3a;
    --accent: #7c6ff7;
    --accent2: #a78bfa;
    --text: #e2e2f0;
    --muted: #888aa0;
    --user-bg: #1e2a3a;
    --bot-bg: #1a2230;
    --tag-bg: #2a2440;
    --pass: #34d399;
    --warn: #fbbf24;
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: -apple-system, 'Segoe UI', sans-serif; min-height: 100vh; }

  /* Layout */
  .layout { display: grid; grid-template-columns: 260px 1fr; height: 100vh; }
  .sidebar { background: var(--surface); border-right: 1px solid var(--border); overflow-y: auto; padding: 20px 0; }
  .main { display: flex; flex-direction: column; overflow: hidden; }

  /* Sidebar */
  .sidebar-title { font-size: 11px; font-weight: 700; letter-spacing: .1em; color: var(--muted); text-transform: uppercase; padding: 0 20px 12px; }
  .dataset-btn {
    display: block; width: 100%; text-align: left; padding: 10px 20px;
    background: none; border: none; color: var(--text); cursor: pointer;
    font-size: 13.5px; border-left: 3px solid transparent; transition: all .15s;
  }
  .dataset-btn:hover { background: rgba(124,111,247,.08); }
  .dataset-btn.active { border-left-color: var(--accent); background: rgba(124,111,247,.12); color: var(--accent2); }
  .dataset-btn .count { font-size: 11px; color: var(--muted); margin-top: 2px; }

  /* Header */
  .header { padding: 20px 28px 16px; border-bottom: 1px solid var(--border); background: var(--surface); }
  .header h1 { font-size: 18px; font-weight: 700; }
  .header .subtitle { font-size: 13px; color: var(--muted); margin-top: 4px; }

  /* Summary panel */
  #summary-panel { padding: 20px 28px; overflow-y: auto; flex: 1; }
  .summary-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 14px; margin-top: 16px; }
  .summary-card {
    background: var(--surface); border: 1px solid var(--border); border-radius: 10px;
    padding: 16px; cursor: pointer; transition: border-color .15s;
  }
  .summary-card:hover { border-color: var(--accent); }
  .summary-card .card-label { font-size: 14px; font-weight: 600; color: var(--accent2); }
  .summary-card .card-count { font-size: 22px; font-weight: 700; margin: 4px 0; }
  .summary-card .card-desc { font-size: 12.5px; color: var(--muted); line-height: 1.5; }
  .total-badge { display: inline-block; background: var(--tag-bg); border: 1px solid var(--border); border-radius: 20px; padding: 4px 14px; font-size: 13px; color: var(--accent2); margin-top: 8px; }

  /* Example viewer */
  #viewer-panel { display: none; flex-direction: column; flex: 1; overflow: hidden; }
  .viewer-header { padding: 14px 28px; border-bottom: 1px solid var(--border); background: var(--surface); display: flex; align-items: center; gap: 12px; flex-wrap: wrap; }
  .viewer-header h2 { font-size: 15px; font-weight: 600; flex: 1; }
  .viewer-header .desc { font-size: 12.5px; color: var(--muted); width: 100%; }
  .nav-controls { display: flex; align-items: center; gap: 8px; margin-left: auto; }
  .nav-btn { background: var(--tag-bg); border: 1px solid var(--border); color: var(--text); padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; transition: background .15s; }
  .nav-btn:hover { background: rgba(124,111,247,.2); }
  .nav-btn:disabled { opacity: .4; cursor: default; }
  .counter { font-size: 13px; color: var(--muted); min-width: 90px; text-align: center; }
  .rand-btn { background: var(--accent); border: none; color: #fff; padding: 6px 14px; border-radius: 6px; cursor: pointer; font-size: 13px; }
  .rand-btn:hover { background: var(--accent2); }

  /* Example content */
  .example-scroll { overflow-y: auto; flex: 1; padding: 20px 28px; }
  .meta-block { background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 14px 18px; margin-bottom: 18px; font-size: 12.5px; line-height: 1.7; }
  .meta-block h3 { font-size: 11px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); margin-bottom: 8px; }
  .meta-row { display: flex; gap: 8px; margin-bottom: 4px; }
  .meta-key { color: var(--muted); min-width: 110px; flex-shrink: 0; }
  .meta-val { color: var(--text); }
  .tag { display: inline-block; background: var(--tag-bg); border: 1px solid var(--border); border-radius: 4px; padding: 1px 8px; font-size: 11px; color: var(--accent2); margin-right: 4px; }

  .turn { display: flex; gap: 12px; margin-bottom: 14px; }
  .turn-label { font-size: 11px; font-weight: 700; letter-spacing: .05em; text-transform: uppercase; min-width: 72px; padding-top: 12px; }
  .turn-label.user { color: #60a5fa; }
  .turn-label.assistant { color: var(--accent2); }
  .turn-bubble {
    flex: 1; background: var(--user-bg); border-radius: 10px; padding: 12px 16px;
    font-size: 14px; line-height: 1.65; border: 1px solid var(--border);
  }
  .turn.assistant .turn-bubble { background: var(--bot-bg); }

  .back-btn { background: none; border: none; color: var(--accent2); cursor: pointer; font-size: 13px; padding: 0; margin-bottom: 12px; display: inline-flex; align-items: center; gap: 4px; }
  .back-btn:hover { text-decoration: underline; }

  .empty { color: var(--muted); font-size: 14px; text-align: center; padding: 60px 0; }
</style>
</head>
<body>
<div class="layout">
  <aside class="sidebar">
    <div class="sidebar-title">Datasets</div>
    <button class="dataset-btn active" data-key="__summary__" onclick="showSummary()">
      Overview
      <div class="count">All datasets</div>
    </button>
    <div id="sidebar-datasets"></div>
  </aside>

  <div class="main">
    <div class="header">
      <h1>MindMate Synthetic Data Viewer</h1>
      <div class="subtitle">Browse training examples for the on-device mental-health companion model</div>
    </div>

    <div id="summary-panel">
      <div id="summary-content"><div class="empty">Loading…</div></div>
    </div>

    <div id="viewer-panel">
      <div class="viewer-header">
        <div>
          <h2 id="viewer-title"></h2>
          <div class="desc" id="viewer-desc"></div>
        </div>
        <div class="nav-controls">
          <button class="nav-btn" id="prev-btn" onclick="navigate(-1)">← Prev</button>
          <span class="counter" id="counter"></span>
          <button class="nav-btn" id="next-btn" onclick="navigate(1)">Next →</button>
          <button class="rand-btn" onclick="randomExample()">Random</button>
        </div>
      </div>
      <div class="example-scroll" id="example-area"></div>
    </div>
  </div>
</div>

<script>
let currentKey = null;
let currentIdx = 0;
let currentData = [];

async function loadSummary() {
  const r = await fetch('/api/summary');
  return r.json();
}

async function loadDataset(key) {
  const r = await fetch('/api/dataset?key=' + key);
  return r.json();
}

async function init() {
  const { datasets, total } = await loadSummary();
  // Sidebar
  const sb = document.getElementById('sidebar-datasets');
  datasets.forEach(d => {
    const btn = document.createElement('button');
    btn.className = 'dataset-btn';
    btn.setAttribute('data-key', d.key);
    btn.onclick = () => selectDataset(d.key, d.label, d.desc);
    btn.innerHTML = `${d.label}<div class="count">${d.count.toLocaleString()} examples</div>`;
    sb.appendChild(btn);
  });
  // Summary cards
  const grid = document.createElement('div');
  grid.className = 'summary-grid';
  datasets.forEach(d => {
    const card = document.createElement('div');
    card.className = 'summary-card';
    card.onclick = () => selectDataset(d.key, d.label, d.desc);
    card.innerHTML = `
      <div class="card-label">${d.label}</div>
      <div class="card-count">${d.count.toLocaleString()}</div>
      <div class="card-desc">${d.desc}</div>`;
    grid.appendChild(card);
  });
  const sc = document.getElementById('summary-content');
  sc.innerHTML = `
    <div style="font-size:22px;font-weight:700;margin-bottom:4px;">Synthetic Training Data</div>
    <div style="font-size:13.5px;color:var(--muted);line-height:1.7;max-width:680px;margin-bottom:8px;">
      All training conversations were generated by a <strong>Qwen3-30B teacher model</strong> running on an A100-80 GPU cluster.
      Each example is a multi-turn dialogue between a user and MindMate, covering emotional support, grief, casual chat,
      emotional pivots, and targeted failure-mode fixes. The final model (genzv2 SFT ck1600) is a <strong>Llama 3.2 3B</strong>
      fine-tuned with QLoRA (4-bit NF4) and runs fully on-device on a Pixel 8a (~5–6 tok/s).
    </div>
    <span class="total-badge">Total: ${total.toLocaleString()} examples across ${datasets.length} datasets</span>
    <div style="height:6px"></div>
    <div style="font-size:11px;color:var(--muted);margin-bottom:16px;">Click a card to browse examples</div>`;
  sc.appendChild(grid);
}

function showSummary() {
  document.getElementById('summary-panel').style.display = 'block';
  document.getElementById('viewer-panel').style.display = 'none';
  document.querySelectorAll('.dataset-btn').forEach(b => b.classList.remove('active'));
  document.querySelector('[data-key="__summary__"]').classList.add('active');
  currentKey = null;
}

async function selectDataset(key, label, desc) {
  document.querySelectorAll('.dataset-btn').forEach(b => b.classList.remove('active'));
  document.querySelector(`[data-key="${key}"]`).classList.add('active');
  document.getElementById('summary-panel').style.display = 'none';
  const vp = document.getElementById('viewer-panel');
  vp.style.display = 'flex';
  document.getElementById('viewer-title').textContent = label;
  document.getElementById('viewer-desc').textContent = desc;
  document.getElementById('example-area').innerHTML = '<div class="empty">Loading…</div>';
  currentKey = key;
  currentIdx = 0;
  const data = await loadDataset(key);
  currentData = data.examples;
  renderExample();
}

function navigate(dir) {
  currentIdx = Math.max(0, Math.min(currentData.length - 1, currentIdx + dir));
  renderExample();
}

function randomExample() {
  currentIdx = Math.floor(Math.random() * currentData.length);
  renderExample();
}

function renderExample() {
  const ex = currentData[currentIdx];
  const total = currentData.length;
  document.getElementById('counter').textContent = `${(currentIdx+1).toLocaleString()} / ${total.toLocaleString()}`;
  document.getElementById('prev-btn').disabled = currentIdx === 0;
  document.getElementById('next-btn').disabled = currentIdx === total - 1;

  let html = '';

  // Meta block
  const meta = ex.meta_scenario || ex.meta_situation || ex.meta || null;
  if (meta) {
    html += '<div class="meta-block"><h3>Scenario metadata</h3>';
    for (const [k, v] of Object.entries(meta)) {
      html += `<div class="meta-row"><span class="meta-key">${k}</span><span class="meta-val">${escHtml(String(v))}</span></div>`;
    }
    if (ex.source) html += `<div style="margin-top:6px"><span class="tag">${escHtml(ex.source)}</span></div>`;
    html += '</div>';
  } else if (ex.source) {
    html += `<div class="meta-block"><span class="tag">${escHtml(ex.source)}</span></div>`;
  }

  // Turns
  const turns = ex.conversations || ex.messages || [];
  turns.forEach(t => {
    const isUser = t.role === 'user';
    html += `<div class="turn ${t.role}">
      <div class="turn-label ${t.role}">${isUser ? 'User' : 'MindMate'}</div>
      <div class="turn-bubble">${escHtml(t.content)}</div>
    </div>`;
  });

  document.getElementById('example-area').innerHTML = html;
  document.getElementById('example-area').scrollTop = 0;
}

function escHtml(s) {
  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>');
}

init();
</script>
</body>
</html>
"""

class Handler(BaseHTTPRequestHandler):
    def log_message(self, fmt, *args):
        pass  # silence access log

    def send_json(self, data):
        body = json.dumps(data).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", len(body))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        qs = parse_qs(parsed.query)

        if path == "/" or path == "/index.html":
            body = HTML.encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", len(body))
            self.end_headers()
            self.wfile.write(body)

        elif path == "/api/summary":
            summary, total = build_summary()
            self.send_json({"datasets": summary, "total": total})

        elif path == "/api/dataset":
            key = qs.get("key", [None])[0]
            if key not in DATASETS:
                self.send_response(404); self.end_headers(); return
            rows = load_dataset(key)
            self.send_json({"key": key, "count": len(rows), "examples": rows})

        else:
            self.send_response(404); self.end_headers()

if __name__ == "__main__":
    port = 7860
    # Pre-load all datasets
    print("Loading datasets…")
    for key in DATASETS:
        rows = load_dataset(key)
        _, label, _ = DATASETS[key]
        print(f"  {label}: {len(rows):,} examples")
    _, total = build_summary()
    print(f"\nTotal: {total:,} examples")
    print(f"\nOpen http://localhost:{port}\n")
    server = HTTPServer(("127.0.0.1", port), Handler)
    server.serve_forever()
